### ISSUE TITLE
Regarding Contribution

### ISSUE THREAD

**Issue by s0md3v** [saeeddhqan/Maryam#1]
Hi there,

By looking at the commits, one can tell that this project is in early stages of development and you are the only on contributing to it.
Maybe the first thing to have other people contributing to it would be to list features and fixes you are trying to implement, You can do this in the "issues" or "projects" section of the repository.

This is a good project and I believe you will make it even better.
Thanks for contributing this to the open source community.

**Comment by saeeddhqan** [comment]
thank you. added
