### ISSUE TITLE
Name origin

### ISSUE THREAD

**Issue by hashimaziz1** [saeeddhqan/Maryam#1]
Curious as to what the inspiration for the name is, as I know it's an Arabic girl's name in use across a lot of the world.

**Comment by saeeddhqan** [comment]
The death of a girl named Maryam and the birth of the Maryam Project

**Comment by hashimaziz1** [comment]
I see. Is it a public case, do you have any more details, or is it more of a personal thing? Searching for Maryam Project on Google brings up quite a lot of projects, unsurprisingly.

**Comment by saeeddhqan** [comment]
If you search for OWASP Maryam, It's easy to find.Those who are going to find, will find. Do you have any suggestions for a name change?
