### ISSUE TITLE
[New Feature] Adding Additional Util Classes

### ISSUE THREAD

**Issue by prakhar-ai** [saeeddhqan/Maryam#105]
We currently lack util classes for several important social networks like Facebook, Twitter, Instagram, LinkedIn etc. I would like to add new classes for these.

**Comment by saeeddhqan** [comment]
You should work with @ktg-123. Both of you work on the search modules.

**Comment by prakhar-ai** [comment]
Great, I'll work together with @ktg-123

**Comment by ktg-123** [comment]
Yeah, actually, these tasks are to be done for the summers as you may have checked in the slack channel. So will start working at that time.

**Comment by saeeddhqan** [comment]
During the summer.
