### ISSUE TITLE
[New Feature] Adding feature to github module

### ISSUE THREAD

**Issue by prince-7** [saeeddhqan/Maryam#106]
I would like to add a feature in the GitHub module that would find the potentially leaked data in the code of the found repositories.

**Comment by saeeddhqan** [comment]
Could you elaborate on the task?

**Comment by prince-7** [comment]
This feature will find the instance of sensitive files like .htpasswd file or passwords or API, NPM tokens that might have been leaked into the public repositories.

**Comment by saeeddhqan** [comment]
It should be a new module.

**Comment by prince-7** [comment]
Ok, I so will make a new module itself. btw osint module, right?

**Comment by saeeddhqan** [comment]
Yes.

**Comment by saeeddhqan** [comment]
Finished by #129
