### ISSUE TITLE
[New Feature] Adding a cloud storage search module

### ISSUE THREAD

**Issue by vikas-kundu** [saeeddhqan/Maryam#109]
I have made a one stop module to search cloud storage services like:
1. Google Drive
2. Dropbox
3. OneDrive
4. Box
Here is a gif of the same: https://asciinema.org/a/jFwVQv3ZechLXb5d6m4hJrzbC
If you say, i can issue the PR.

**Comment by saeeddhqan** [comment]
@vikas-kundu we need the origin sources along with the search engine results. As I mentioned about TikTok.
Could you do it? For which one is possible.

**Comment by vikas-kundu** [comment]
For these sites, it is not possible to search directly. i.e https://drive.google.com/file/d/something won't work as the rest of URLs are randomized. For them i can only search through engines. 
If you want, i can add a function which will scrap the content in the links obtained via search engines.

**Comment by saeeddhqan** [comment]
Okay, got it.
You can make your PR.

**Comment by saeeddhqan** [comment]
Done by #112
