### ISSUE TITLE
[New Feature] Adding a telegram search module

### ISSUE THREAD

**Issue by vikas-kundu** [saeeddhqan/Maryam#118]
I have made a module that searches for handles, phone numbers, links in telegram groups listed online. Here is a gif of the same: https://asciinema.org/a/dw8aekqSrgxOyUWCp1FHKK4rM. Let me know if i can issue PR.

**Comment by saeeddhqan** [comment]
You can use this as an additional source along with other sources: 
1- https://telegramchannels.me/search?search=toefl&type=channel

**Comment by saeeddhqan** [comment]
Done by #122
