### ISSUE TITLE
[New Feature] Add a scholar module

### ISSUE THREAD

**Issue by z3y50n** [saeeddhqan/Maryam#119]
We already have an arxiv search module.

My idea is to create 2 more utils for [Microsoft Academic](https://academic.microsoft.com/home) and [Google Scholar](https://scholar.google.com/)

And create a `scholar`/`academic`/`scientific` (choose any name you want :P) search module that includes all 3 sources (maybe more).

If approved I can start working on it right away

**Comment by saeeddhqan** [comment]
Work with @k4u5h1k. He wants to do the same with other sources. Put it all together and make a new module to search.

**Comment by ktg-123** [comment]
Actually these modules were also part of the Util class in the list uploaded on the slack channel and I was going to work for these in the summer. Could you please let me know that whether we are working on these sources right now and should I remove it from my proposal?

Regards
Kunal

**Comment by z3y50n** [comment]
Sure I am willing to let you work on them during the summer since it is part of your proposal.

**Comment by k4u5h1k** [comment]
I have already written a module for Google scholar. But there is a catch,
Google scholar starts asking for a captcha when you hit a limit of around 30 requests, no idea after how long it whitelists again. Also I haven't tested it much so will not push.
Good luck! pm me on slack if you would like the code or have questions.
