### ISSUE TITLE
linkedin

### ISSUE THREAD

**Issue by shanow7** [saeeddhqan/Maryam#12]
could you show module search/linkedin?

**Comment by saeeddhqan** [comment]
What do you mean? Is there any problem with _search/linkedin_? Or you need to know about this module?

**Comment by shanow7** [comment]
can you supplement the modules with more videos, e.g. linkedin

https://github.com/saeeddhqan/Maryam/wiki/modules

**Comment by saeeddhqan** [comment]
Done, [linkedin](https://github.com/saeeddhqan/Maryam/wiki/modules#linkedin-tool).

**Comment by shanow7** [comment]
thx :)Temat: Re: [saeeddhqan/Maryam] linkedin (#12)Data: 2020-09-03 13:48Nadawca: "Saeed Dehqan" Adresat: "saeeddhqan/Maryam" ; DW: "jan bor" ; "Author" ; 
Done, linkedin.
