### ISSUE TITLE
[New Feature] Add lxml support for scrapping in util classes

### ISSUE THREAD

**Issue by ktg-123** [saeeddhqan/Maryam#126]
I would like to take this and will make appropriate changes in search modules as well

**Comment by ktg-123** [comment]
@saeeddhqan should we close this issue ? As I think its fixed in e7505aa2b004b3261b5cd9e94b6b95cf8ffd5b3b .

**Comment by saeeddhqan** [comment]
You can do it for the rest classes.

**Comment by ktg-123** [comment]
Will we be modifying all the util classes to use lxml format? If so, I shall start by making a PR  and include all of the changes in that only.

**Comment by saeeddhqan** [comment]
yes

**Comment by ktg-123** [comment]
Thanks for letting me know. I would soon make a PR and start working on it.
I have also modified the title accordingly.
