### ISSUE TITLE
Can't use wapps feature.

### ISSUE THREAD

**Issue by jan-kwiatkowski** [saeeddhqan/Maryam#13]
I ve been trying to use wapps command in Mayram but i got UnicodeDecodeError for python 3.6 so i checked for python3.7 but got KeyError.

`[maryam][default] > wapps -d example.com
[!] File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode.
[!] UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1350: ordinal not in range(128).`

The traceback isn't very helpful. Tried to browse wapps.py and module.py but no clue.
Just to verify - maryam should be run with wich python?

**Comment by saeeddhqan** [comment]
**You should run maryam on python 3.8.x. 
Check it and let me know if you have any problems with it.**


[maryam][default] > wapps -d owasp.org
[\*] WAPPS
[\*]     Cloudflare : http://www.cloudflare.com
[\*]     Ruby : http://ruby-lang.org
[\*]     Varnish : http://www.varnish-cache.org
[\*]     Ruby on Rails : https://rubyonrails.org
[\*]     GitHub Pages : https://pages.github.com/
[\*]     Fastly : https://www.fastly.com
[maryam][default] >
