### ISSUE TITLE
[New Feature] Dedicated Twitter engine to make use of its dorks

### ISSUE THREAD

**Issue by k4u5h1k** [saeeddhqan/Maryam#131]
Twitter has fantastic search capabilities,   

 ![Screenshot 2021-04-02 at 10 57 00 AM](https://user-images.githubusercontent.com/59250093/113383732-29c9ad00-93a2-11eb-993a-492a647a75be.png)

(taken from https://osintcurio.us/2019/10/01/searching-instagram-part-2/)

The implementation of this in the current twitter search module would be complicated and inconsistent due to usage other engines to scrape twitter links.

A dedicated twitter engine would not only allow more accurate searches in its own module, but also add the capability for using it as a standalone engine to search for tweets and  metadata relevant to other modules as well.

**Comment by k4u5h1k** [comment]
@saeeddhqan as this is a major rework should I add it to my gsoc proposal?

**Comment by prakhar-ai** [comment]
Hi @k4u5h1k, I already have a detailed description for a Twitter util class in my proposal, which I've shown to @saeeddhqan (also listed in #105 ). Maybe we would work on it together if you'd like. There are also a number of other util classes that need to be added during the first part of the summer, you could choose one of them if you want.

**Comment by k4u5h1k** [comment]
Oh, my bad! I would love to help you with it but we'll decide that later. Closing this now.
