### ISSUE TITLE
[New Feature] Adding Pinterest module

### ISSUE THREAD

**Issue by anuran-roy** [saeeddhqan/Maryam#134]
Pinterest is an underused platform for OSINT gathering. But Pinterest boards are really good sources of target information, often containing even sensitive information. A new Pinterest module would be great. 

Here is an article supporting my claim: [Forbes Article](https://www.forbes.com/sites/joegray/2018/12/29/pinning-the-osint-to-the-board/?sh=603fc388b7ed)

Here is a screenshot of a paragraph from the same article:
 
![image](https://user-images.githubusercontent.com/76481787/113398443-3b1fb300-93bc-11eb-9191-531423cd6832.png)

**Comment by saeeddhqan** [comment]
How do you want to write it? with search engines? or original source? or both of them? both of them are great.

**Comment by prakhar-ai** [comment]
We can create three different categories for Usernames, Collections, and Pins

For Usernames,

`pinterest.com/'username'`

for Collections,

`pinterest.com/'username'/'collection'`

for Pins,

`pinterest.com/pin/'pin_id'`

Only pins can be queried directly, using `https://www.pinterest.com/search/pins/?q=query` but this seems very hard to scrape. I think we should stick to using search engines for now since they provide a pretty good result in the case of Pinterest.

**Comment by anuran-roy** [comment]
To be honest, I think we should go with search engines. As @prakhar-ai said, there has been really good improvements in search engine scraping. Also, I looked up online about the Pinterest Developer's API. The Pinterest Developer's API is somewhat restrictive in my opinion. 
We can also include a user reverse search, since we can map both ways: pins to users and users to pins. 

Should we try implementing that as well?

**Comment by prakhar-ai** [comment]
> We can also include a user reverse search, since we can map both ways: pins to users and users to pins.

I'm not sure how you intend to do that. Pin urls don't seem to mention the username anywhere. 

You could take a look at the other search modules, and It should be elementary to build a search module using the url patterns I mentioned above. You can open up a PR and I'll help you if you need any guidance.

**Comment by anuran-roy** [comment]
Umm... I observed something... I think that the pre-existing LinkedIn script and the intended Pinterest script have a lot in common. Can I reuse the code? If so, how do I credit the original author of the LinkedIn Script? @saeeddhqan ?

Also... This involves reworking on quite a few parts of Maryam. Can I include it in my GSoC proposal?

**Comment by saeeddhqan** [comment]
Can I reuse the code? yes
 If so, how do I credit the original author of the LinkedIn Script? your name
 Can I include it in my GSoC proposal? yes

**Comment by necrose99** [comment]
@saeeddhqan @anuran-roy  https://github.com/qeeqbox/social-analyzer has 200 apis might be worth a look.
