### ISSUE TITLE
 [New Feature] Adding URL screenshot module 

### ISSUE THREAD

**Issue by vikas-kundu** [saeeddhqan/Maryam#137]
There is a way to view every profile of Linkedin without triggering the authwall. Similarly, every content can be viewed without getting blocked on any site by using the [Google Mobile friendly test.](https://search.google.com/test/mobile-friendly). Not only the website screenshot but it also shows the HTML code (see image: https://ibb.co/Prd79hk). But there is a captcha to use it. 

So, i found another alternative that is the [Bing Mobile friendliness test](https://www.bing.com/webmaster/tools/mobile-friendliness). It has no captcha and i have mapped the APIs. So, it can be used to view a mobile screenshot of any profile or website without getting blocked (see image:  https://ibb.co/LkBKx4b). I can implement a module or util class, whatever you say.

**Comment by saeeddhqan** [comment]
Definitely a great idea!
 I can implement a module or util class, whatever you say? both of them.
 Another crazy thing is you can use the "Googlebot smartphone" user-agent for LinkedIn to see the profiles and search through it without auth: for this we need a new util class and a new module that extracts information, profiles, for a specific profile.

**Comment by rachejazz** [comment]
Hey @vikas-kundu hoping this does not collide with screenshotapi.net or urlscan.io screenshots, since im adding them during the summers under Wayback Machine module

**Comment by vikas-kundu** [comment]
@rachejazz This is different from both the resources you mentioned because:
1. For urlscan.io you get this error while scanning linkedin profiles or any other sensitive stuff "The submitted domain is on our blacklist. For your own safety we did not perform this scan." (See image: https://ibb.co/1KY2PVL)
2. For screenshot api, if you want screenshot of more than one profile, you will hit the authwall. (See image: https://ibb.co/gFbJMxr)

Moreover, the mobile friendliness test doesn't even give you the full screenshot but just a mobile sneak peak view. However, if you still feel it collides with your project ideas, feel free to take the source code from me and implement it as you like.

**Comment by vikas-kundu** [comment]
> Another crazy thing is you can use the "Googlebot smartphone" user-agent for LinkedIn to see the profiles and search through it without auth: for this we need a new util class and a new module that extracts information, profiles, for a specific profile.

I tried with that too but  hit the authwall as maybe they also check the IP or something along with that.

**Comment by rachejazz** [comment]
@vikas-kundu nice!! So maybe once you figure out and add this module, I can add a flag option in mine like "Would you like to view it in Maryam's screenshot module?" , which be will this one written by you.
Am I making any sense?

**Comment by vikas-kundu** [comment]
@rachejazz i will be implementing a util class too, so you can call that in your modules and use it as a source.

**Comment by rachejazz** [comment]
Good stuff. Thanks

**Comment by saeeddhqan** [comment]
> 
> 
> > Another crazy thing is you can use the "Googlebot smartphone" user-agent for LinkedIn to see the profiles and search through it without auth: for this, we need a new util class and a new module that extracts information, profiles, for a specific profile.
> 
> I tried with that too but hit the authwall as maybe they also check the IP or something along with that.


I tested it a while ago, it worked out, but now it doesn't work. weird

**Comment by vikas-kundu** [comment]
> I tested it a while ago, it worked out, but now it doesn't work. weird

What user agent did you use? I tried with this:

`Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F70 Safari/600.1.4 (compatible; Googlebot /2.1; +http://www.google.com/bot.html)`

**Comment by saeeddhqan** [comment]
"Googlebot smartphone"

**Comment by saeeddhqan** [comment]
Finished by #145
