### ISSUE TITLE
[New Feature] Dealing with Recaptcha trigger events

### ISSUE THREAD

**Issue by anuran-roy** [saeeddhqan/Maryam#138]
Just as I tried to scrape LinkedIn for a second time using the LinkedIn script that uses Google as a search engine, the program showed the output that the Google Recaptcha was triggered. 

Screenshot:

![image](https://user-images.githubusercontent.com/76481787/113455683-e9614200-9428-11eb-837f-a8b4d56fbc36.png)

Now this issue is something I am trying to work on. I have a rough plan to tackle this problem. 

The solution I am thinking of is to use the method of rotating proxies. We can get a list of free proxies from online to do our job. 

I haven't yet found a module for rotating proxies. So as per my guess, this solution involves some restructuring of the code base. 

Any thoughts about it?

**Comment by saeeddhqan** [comment]
It should be an option for users. Or a framework option that finds free proxies and uses them in the requests. we can also have a module to show a list of free proxies. e.g:
`set autoproxy true`
Then, if we got a problem with captcha, we start scraping free proxies and set them one by one.
This is a great idea.

**Comment by k4u5h1k** [comment]
Just a suggestion. For the dark web portion we have to add tor to maryam anyway and tor supports rotating ips internally. Might be worth considering too.

**Comment by anuran-roy** [comment]
From my experience, there is a problem with Tor nowadays- it's widely recognizable and many non-darkweb websites don't allow it. It'll trigger Captchas from not only the search engines but the websites themselves as well. 
Any idea or suggestions regarding how to work through this? 🤔

**Comment by vikas-kundu** [comment]
https://github.com/stamparm/fetch-some-proxies
This is a good project to take inspiration from

**Comment by k4u5h1k** [comment]
I did read about exit nodes being blacklisted but is it that widespread? I did not know. But in any case I dont think **every** exit node can be blacklisted so `while haveCaptcha: rotateip()` will always solve the issue. Anyhow let's keep this as a plan b.

**Comment by anuran-roy** [comment]
For now, I have a sample script in a repo I recently made and am working on. The program uses the libraries **lxml** and **requests**. 

The link is: [Drax/modules/proxy_fetch.py](https://github.com/anuran-roy/drax/blob/main/modules/proxy_fetch.py) 

This module simply fetches a list of proxies from sites and stores them in a file. 

As for the claim that `while haveCaptcha: rotateip()` will always solve the issue, it might be very well possible that finding the proxies alone will prove to be a time-consuming task, given that many (if not most) of the exit nodes of the Tor Network have become blacklisted. The solution is very well possible, but may not be feasible. 

These are just my observations. You're free to disagree :-D

**Comment by z3y50n** [comment]
I have also written a script in the past for fetching random proxies from [sslproxies](https://www.sslproxies.org)

```
def set_proxies():
    result = requests.get("https://www.sslproxies.org", headers = headers)
    soup = BeautifulSoup(result.content, "html.parser")
    proxies_table = soup.find(id = "proxylisttable")
    
    for row in proxies_table.tbody.find_all("tr"):
        proxies.append({
            "http": f"http://{row.find_all('td')[0].string}:{row.find_all('td')[1].string}",
            "https": f"http://{row.find_all('td')[0].string}:{row.find_all('td')[1].string}"
        })
```

From my experience though crawling websites like google using rotating proxies isn't a very effective method since they have very good protection methods and also google has changed its policy and is more restrictive in allowing you to crawl its website.

**Comment by anuran-roy** [comment]
Umm... maybe then we should consider notifying users to change to DuckDuckGo? I hope it doesn't, although I don't have proper evidence to back my claim.

**Comment by saeeddhqan** [comment]
@k4u5h1k, @anuran-roy,  the experiment is simple. In the google util class, if the captcha triggered, run a function that rotates the IP:

```python

			if req.status_code in (503, 429):
				req = self.framework.error('[GOOGLE] Google CAPTCHA triggered.')
				rotateip()
				continue
```

 Next, use the google module to search with a high dose: **time ./maryam -e google -q "google" -l 50 -c 50**

**Comment by k4u5h1k** [comment]
Yep I only said keep the tor idea as backup if none of the proxies in your list work for some reason. @anuran-roy are you implementing this or should someone else (read 'I')?

**Comment by anuran-roy** [comment]
I really regret missing that part. 😅
Yeah then I am gonna go forward with implementing this. @k4u5h1k

**Comment by k4u5h1k** [comment]
No problem, go ahead.

**Comment by anuran-roy** [comment]
@saeeddhqan @k4u5h1k  I have implemented the proxy rotating mechanism inside the google util class. 

But I have a small question now. Where do I modify the code such that `set autoproxy True` triggers those scripts? I know I am sounding like a novice... But I am really unable to find it.  😅

**Comment by saeeddhqan** [comment]
Could you show the results?
in the initial file: [here](https://github.com/saeeddhqan/Maryam/blob/2f94d510ecf16ecd72741e2b6adfb5a4a0909372/core/initial.py#L79)

```python

		self._global_options_['autoproxy'] = ('autoproxy', False, False, '<description>')
```

**Comment by anuran-roy** [comment]
Umm, I can send the screenshot if I run the program standalone. This is because since I haven't yet encapsulated the methods inside my module in a class, Maryam is disabling it. 
Can I send the working of the standalone module? @saeeddhqan ?
Also, I needed to make a few changes to the google.py util class. Now when I start Marym, it's showing that Maryam is disabling it because of some inconsistent indentation, but I am not able to find. 😅

**Comment by rachejazz** [comment]
@anuran-roy happens when spaces are typed instead of tabs for same amount of indentation. Just backspace that line and press tab again

**Comment by saeeddhqan** [comment]
Make pr, we will work on it.

**Comment by anuran-roy** [comment]
I developed an experimental script for now. I would include Tor for later, but I am facing difficulties while trying to integrate. Here is the code that I made:
[Proxy.py](https://github.com/anuran-roy/Maryam/blob/dev-pinterest-module/core/util/proxy.py)

And here's what I modified in /core/util/google.py:

[Google.py](https://github.com/anuran-roy/Maryam/blob/dev-pinterest-module/core/util/google.py)

Here is the working of proxy.py in verbose mode:

![image](https://user-images.githubusercontent.com/76481787/113597031-bbfadb00-9658-11eb-93ba-5ccea16e4e45.png)

PS: I also added the `set autoproxy` option in [initial.py](https://github.com/anuran-roy/Maryam/commit/794acad8d044e7add4c1cbce979ecade583f98fc) , as @saeeddhqan told.

**Comment by k4u5h1k** [comment]
what are the steps to reproduce this captcha issue.
I've run linkedin several times and it works fine for me
