### ISSUE TITLE
[New Feature] Add gigablast.com

### ISSUE THREAD

**Issue by k4u5h1k** [saeeddhqan/Maryam#142]
They have a public API this should be simple enough. I'll take it.

**Comment by saeeddhqan** [comment]
we need to scrape the API and the web page as well.

**Comment by k4u5h1k** [comment]
why

**Comment by k4u5h1k** [comment]
API gives everything on the webpage in json with a ton of fields

**Comment by k4u5h1k** [comment]
Ive already made it with the API
![Screenshot 2021-04-04 at 1 37 25 PM](https://user-images.githubusercontent.com/59250093/113502594-e65e7280-954a-11eb-96a8-5299691f3747.png)
Also there is no blacklisting. What additional advantage would the webpage give @saeeddhqan ?

**Comment by saeeddhqan** [comment]
rate-limit?

**Comment by k4u5h1k** [comment]
There is no mention of it. There has to be one but I didnt run into any issues while testing.
I will submit the pr and if you hit a rate-limit, I will add nonapi support.

**Comment by saeeddhqan** [comment]
Finished by #143
