### ISSUE TITLE
[New Feature] Ip-profiling util, module, dns enumeration

### ISSUE THREAD

**Issue by rachejazz** [saeeddhqan/Maryam#146]
I'm adding the urls:
https://dns-lookup.com
https://www.ipqualityscore.com/domain-reputation
As a util class 
Addition to domain_reputation
Dns_search for dns lookup
Urlscanner module for Threat Analysis on phishing scam.
I wish to add a different module for everything related to url check. That can have all the above ones as util classes (including urlscan.io added before)

Waiting for approval

**Comment by saeeddhqan** [comment]
https://www.ipqualityscore.com/domain-reputation accept
https://dns-lookup.com/ not now
I wish to add a different module for everything related to url check. That can have all the above ones as util classes (including urlscan.io added before): no

**Comment by rachejazz** [comment]
Anything wrong with the dns lookup util class?
It can extract spf records of a domain and also get whether the mx records are valid ones or not.
Also the a records can get us hidden subdomains!
That's how you mark some as phishing emails too.. Wouldn't that be cool?!
@saeeddhqan
