### ISSUE TITLE
[New Feature] Automating workflows in OWASP Maryam

### ISSUE THREAD

**Issue by anuran-roy** [saeeddhqan/Maryam#150]
In many cases of OSINT gathering, we have repetitive tasks.  For example, looking up details on some username/email involves a search in the different social media first, followed by a possible phone number lookup (if found), and then geolocating the phone number. 

Since these tasks are repititive, I was suggesting a new section called **templates** , that will allow users to quicken up their OSINT gathering. I guess it'll be even better if it's made to be interactive. 

Maybe we have to make some new commands like:  `use template <template_name>` ?

For now, I think we shouldn't think of implementing AI in any way, because it will take up precious computing power.

What are your thoughts about it? 😅

**Comment by saeeddhqan** [comment]
For now, I think we shouldn't think of implementing AI...: Don't think so, we use tricks that won't take much time and computing. If so, it's worth it!
I was suggesting a new section called templates , that will allow users to quicken up their OSINT gathering: I thought about it. Yes, the users definitely need these modules.

**Comment by anuran-roy** [comment]
Sir, can you please elaborate as to which tricks you are telling about? I will learn them then, and implement them in other use cases as well. 😅
