### ISSUE TITLE
[Bug] Issue with self.request method

### ISSUE THREAD

**Issue by vikas-kundu** [saeeddhqan/Maryam#151]
As per the documentation, the self.request method is defined as follows:

`req = self.request(url=url, timeout=timeout, headers={}, rand_agent=True,    cookie=cookie, auth={}, redirect=False, method="POST", content='', payload={}, proxy=proxy)`

However on running:
`req = self.(url=url, rand_agent=True)
`
The following error occurs:
`[!] TestCodeError: request() got an unexpected keyword argument 'rand_agent'.
`

This is caused because in the core file, kwargs['rand-agent'] is passed as it is to the original  python requests module but it does not understand any such parameter. To resolve it, adding the following code snippet below the header variable will do the trick:

```
if kwargs.get('rand_agent') is not None: #If exists rand_agent option
  if headers['user-agent']: #If it is True
    headers['user-agent'] = rand_uagent.main().get #Call random agent function and set the param user-agent
  else: #Otherwise set default user agent
    headers['user-agent'] = headers.get('user_agent', False) or self._global_options['agent']

  kwargs.pop('rand_agent',None) #Finally remove it from the kwargs dict

````		
Now, this problem is also present for other prams like cookie, redirect, payload, content and proxy.

- For cookie, renaming it to cookies in the wiki will do as requests has a parameter named cookies.
- For redirect, renaming it to allow_redirects in the wiki will do as requests has a parameter named allow_redirects.
- Payload and content seems like redundant words so remove it from wiki or let me know how they need to work so i can figure out the implementation.
- For proxy, i can add a method similar to rand_agent
I can work on it and issue a PR if you say.

**Comment by saeeddhqan** [comment]
we should use global options.
The wiki page updated.
