### ISSUE TITLE
 [New Feature] Adding a WorldCat module

### ISSUE THREAD

**Issue by vikas-kundu** [saeeddhqan/Maryam#152]
Library Genesis is a file-sharing based shadow library website for scholarly journal articles, academic and general-interest books, images, comics, and magazines. I can add a comprehensive module to search for a book or article in that.

**Comment by ktg-123** [comment]
HI @vikas-kundu! Since I will be working on the addition of new sources, this task is already in my proposal for summer under the util class. However, if you have prepared the module then you may ask @saeeddhqan and push it. I would remove it.

Regards 
Kunal

**Comment by vikas-kundu** [comment]
@ktg-123 Sorry I didn't know about that. No I haven't prepared it yet so will skip it. What about a Worldcat module? Is that in your proposal too?

**Comment by ktg-123** [comment]
Thanks! @vikas-kundu , No you can surely go ahead with the WorldCat module

**Comment by vikas-kundu** [comment]
@saeeddhqan since Library genesis is already added to Kunal's GSOC proposal, can I change the title to Adding a WorldCat module?

**Comment by saeeddhqan** [comment]
yes

**Comment by saeeddhqan** [comment]
finished by #167
