### ISSUE TITLE
[New Feature] Norton Check

### ISSUE THREAD

**Issue by rachejazz** [saeeddhqan/Maryam#154]
Can we have this? Still unsure.
![image](https://user-images.githubusercontent.com/42383989/113913321-d0c2a480-97f9-11eb-905d-988a3271e902.png)

https://safeweb.norton.com

**Comment by saeeddhqan** [comment]
This is good. after it, I think that's enough for domain reputation. It causes wrong results.

**Comment by rachejazz** [comment]
Then let me see better ones :'D 
If it's the last, then it should be the best one added

**Comment by anuran-roy** [comment]
I think we should average the results from quite a few online reputation sites. We can assign scores with different flags. For example:

1. Malicious = 0
2.  Potentially malicious = 0.25
3. Unknown = 0.5
4. Seems safe = 0.75
5. Verified = 1

We can then set a threshold value (say 0.5) for the site, and evaluate the overall safety using the same scale, or a different scale. I think that would reduce the chances of wrongly identifications.

A few other online reputation sites like this can be those of McAffee, Kaspersky, Web of Trust (WOT), Avast, and TrustPilot.

**Comment by rachejazz** [comment]
@anuran-roy yeaah, I'm looking into these. Most of them have a paid API or a captcha, so not able to scrape :'(

**Comment by anuran-roy** [comment]
> @anuran-roy yeaah, I'm looking into these. Most of them have a paid API or a captcha, so not able to scrape :'(

[ThreatConnect API Docs](https://docs.threatconnect.com/en/latest/rest_api/quick_start.html#using-the-api). This one is free.

**Comment by saeeddhqan** [comment]
It needs auth: https://docs.threatconnect.com/en/latest/rest_api/quick_start.html#authentication

**Comment by anuran-roy** [comment]
Maybe we should give users an option to use the ThreatConnect API? Professionals and organizations may very well need it. 😅

**Comment by rachejazz** [comment]
I believe this can fit for the OSINT database one. Let me have the module done during summers and then you can add this a source (or not, depends on saeed).
Hang in there till summer!
