### ISSUE TITLE
[New Feature] Mac and IP changer

### ISSUE THREAD

**Issue by rishi23root** [saeeddhqan/Maryam#162]
USE random Mac and IP addresses for more anonymousness in each search

**Comment by saeeddhqan** [comment]
Give me example.
Thanks

**Comment by rishi23root** [comment]
I am working on my code, for now 
 - MAC use something like - https://github.com/feross/SpoofMAC
 - IP use something like - https://github.com/ruped24/tor_ip_switcher or https://github.com/FDX100/Auto_Tor_IP_changer

**Comment by saeeddhqan** [comment]
MAC use something like: no
IP use something like: join #148 we want to do it by free proxies and tor proxies.

**Comment by saeeddhqan** [comment]
looks good?
