### ISSUE TITLE
[New Feature] Adding dnsdumpster search module

### ISSUE THREAD

**Issue by rishi23root** [saeeddhqan/Maryam#169]
DNSdumpster.com is a FREE domain research tool that can discover hosts related to a domain. Finding visible hosts from the attacker's perspective is an important part of the security assessment process.
It creates a very detailed report

It has a [site](https://dnsdumpster.com/) from which we can extract data 
or 
it also has a [git repo](https://github.com/nmmapper/dnsdumpster) for command-line *written in python*

@saeeddhqan can we implement this? If yes, can I include it in my GSoC proposal?

**Comment by rachejazz** [comment]
already added.
Check dns_search module sources

**Comment by saeeddhqan** [comment]
@rishabhjainfinal please check the TODO list in the [projects](https://github.com/saeeddhqan/Maryam/projects) section and select one of them, add it to your proposal and make an issue and pr.

**Comment by necrose99** [comment]
https://pypi.org/project/dnsdumpster/
