### ISSUE TITLE
[New Feature] Adding a module to search for books in zlibrary

### ISSUE THREAD

**Issue by vikas-kundu** [saeeddhqan/Maryam#170]
Source: https://1lib.in

**Comment by saeeddhqan** [comment]
https://2lib.org?

**Comment by vikas-kundu** [comment]
Yes both are same but since my IP is India so it showed me the nearest server. When I tried to access it from Tor via exit node of Netherlands, it showed  https://1lib.nl . So, what i will do is first scrape the nearest server from https://z-lib.org/ and then start with searching books.

**Comment by saeeddhqan** [comment]
finished by #184
