### ISSUE TITLE
 [New Feature]  Adding sepiasearch.org search module

### ISSUE THREAD

**Issue by rishi23root** [saeeddhqan/Maryam#173]
**Sepia Search is a video search engine optimized for PeerTube channels**

**Comment by saeeddhqan** [comment]
Check their API as well. if you need help you can check [this](https://github.com/searx/searx/blob/master/searx/engines/sepiasearch.py) code

**Comment by rishi23root** [comment]
> Check their API as well. if you need help you can check [this](https://github.com/searx/searx/blob/master/searx/engines/sepiasearch.py) code

Thanks 
my demo code 
```
import requests, json
from pprint import pprint

headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36'}
url = 'https://sepiasearch.org/api/v1/search/videos?'
params = {'search': 'This is the way', 'boostLanguages[]': 'en', 'start': 10, 'count': 10, 'sort': '-match'}
response = requests.get(url, params=params)
pprint(response.json())
print(response.status_code)
```
I will add more features soon
