### ISSUE TITLE
[New Feature] Adding photon.komoot.io

### ISSUE THREAD

**Issue by rachejazz** [saeeddhqan/Maryam#190]
Simple api, will be better to integrate after openstreetmap by @ktg-123 gets merged.
Will displaying it as a table be better?

**Comment by saeeddhqan** [comment]
Will displaying it as a table be better? sounds good

**Comment by rachejazz** [comment]
@saeeddhqan apologies for the latency. Had to finish other business before resuming with Maryam
I am seeing openstreetmap as a module. I am adding photon as a util class, but...
Should i add photon as a separate module too?
