### ISSUE TITLE
[New Feature] ASN Researcher

### ISSUE THREAD

**Issue by cabr4** [saeeddhqan/Maryam#192]
I want to add:
https://api.bgpview.io/search?query_term=query_term
as osint/asn_researcher.py

Here´s the documentation:
https://bgpview.docs.apiary.io/#reference/0/search/search-resources-by-asn,-ip,-prefix,-name,-descitpion

Waiting for aproval

**Comment by saeeddhqan** [comment]
It should be a util class. because we can use it for finding emails. approved
