### ISSUE TITLE
[New Feature] Extracting d.js file for duckduckgo and sending request to it

### ISSUE THREAD

**Issue by vikas-kundu** [saeeddhqan/Maryam#195]
While normally using requests, it is not possible to get .js files, something like selenium would be too heavy for the module. So, another way is to use the google pagespeed api. 

For example, requesting this:

```
query = self.options['query'] 
url = f"https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=https://duckduckgo.com/?q={query}"
response = self.request(url)

```
will return a JSON format data in which, the d.js file can be find using regex from the following key

```
for i in response.json()['lighthouseResult']['audits']['bootup-time']['details']['items']:
    if re.search(r'https://links.duckduckgo.com/d.js.*', i['url']):
        d_js_url = i['url']

```
later, request can be sent to that d_js_url and data can be scraped. Although, I think this API is more than sufficient but if you say I can add another source too like 'https://www.webpagetest.org/' which will show js files on the search page that can be filtered using regex. I just want to know that:

- will it be a separate module?
- what data to scrap from d.js link?

**Comment by z3y50n** [comment]
Doesn't pagespeed api require a key?

**Comment by vikas-kundu** [comment]
No. If you don't make more than 100 requests per second and 25,000 requests per day, it works fine without a key.

**Comment by vikas-kundu** [comment]
@saeeddhqan will this be a separate module?

**Comment by saeeddhqan** [comment]
Yes.
