### ISSUE TITLE
[New feature] Microsoft Office365 Enumeration

### ISSUE THREAD

**Issue by rachejazz** [saeeddhqan/Maryam#196]
Following article regarding enumeration on o365 tells you whether an email address (or a domain name) has a valid o365 instance active or not
https://bond-o.medium.com/microsoft-office-365-enumeration-58f9b5ba21c8
From this we find out the following-

1. If we have a domain (from dns_search of Maryam)
There are three possible results:
Unknown = No O365 instance for that domain
Federated = O365 is federated
Managed = O365 is managed directly by Microsoft

2. If we have a breached email address (from email_pwned module)
· 0 = Valid Email Address
· 1 = Invalid Email Address; does not exist in hosted O365 domain
· 5 = Valid Email Address
· 6 = Valid Email Address

Example request:
```
curl https://login.microsoftonline.com/getuserrealm.srf?login=username@google.com 
{
"State":4,"UserState":1,
"Login":"username@google.com",
"NameSpaceType":"Managed",
"DomainName":"google.com",
"FederationBrandName":"google.com",
"CloudInstanceName":"microsoftonline.com",
"CloudInstanceIssuerUri":"urn:federation:MicrosoftOnline"
}
```

**Comment by rachejazz** [comment]
A helpful idea from @anuran-roy :) from his #156 issue, this can be start towards that issue?

**Comment by anuran-roy** [comment]
Umm... I have a doubt... 😅 
Are you thinking to directly dump the fields, or do you intend to process them for omitting fields with empty values (like: NA or other equivalents)?
I mean, if we can filter out those incomplete (or empty) fields and keep only unique fields, then we can directly increase the info retrieval speed later, like by using dictionaries. 

what do you think @rachejazz @saeeddhqan ?

**Comment by rachejazz** [comment]
We have --api for "dumping" :)
I will process the json data of course, that would make sense out of every output. That's how it can be used on other modules during the same enumeration event

**Comment by anuran-roy** [comment]
Hmm... that's a nice idea. This way we can include a Maryam-generated `remarks` field in the OSINT explainability module's output  which will pertain to this module as of now. That will contain remarks as to how the data obtained this module can be used.

**Comment by rachejazz** [comment]
Yes! We can discuss about this when I come to add this
