### ISSUE TITLE
Requirements file

### ISSUE THREAD

**Issue by silverNitrateIon** [saeeddhqan/Maryam#2]
Can someone please include a requirements file? It's rather opaque what is needed to property run this. Thanks!

**Comment by saeeddhqan** [comment]
Do you have an error when running the program?
In the new version I add it.

**Comment by adrhmnhkm** [comment]
[!] Module 'osint/docs_search' disabled. Dependency required: ''cookielib''.
[!] Module 'osint/social_nets' disabled. Dependency required: ''cookielib''.
[!] Module 'osint/godork' disabled. Dependency required: ''cookielib''.
[!] Module 'osint/onion_search' disabled. Dependency required: ''cookielib''.
[!] Module 'osint/email_search' disabled. Dependency required: ''cookielib''.
[!] Module 'osint/web_crawler' disabled. Dependency required: ''cookielib''.
[!] Module 'osint/dns_search' disabled. Dependency required: ''cookielib''.
[!] SyntaxError: Missing parentheses in call to 'print'. Did you mean print(e.message)?

**Comment by saeeddhqan** [comment]
Added
