### ISSUE TITLE
 [New Feature] Adding btdig.com module and util class 

### ISSUE THREAD

**Issue by vikas-kundu** [saeeddhqan/Maryam#206]

**Comment by rachejazz** [comment]
Does it give a captcha for you? It did for me. 
Also, it's blocked in my country lol. Had to use proxy

**Comment by vikas-kundu** [comment]
> Does it give a captcha for you? It did for me.
> Also, it's blocked in my country lol. Had to use proxy

Thanks for pointing out, actually I had enabled ESNI in firefox so it bypassed the block and worked. But now that I checked it is blocked, it can be scraped via proxies. However the main issue is of the Google Captcha. Tried with Cloudscraper but didn't work. @saeeddhqan I see no way to bypass the Google Captcha so you should remove it from the TODO list. Should i close this issue?

**Comment by vikas-kundu** [comment]
One way around it can be to ask user to solve the Google catpcha first and use those cookie obtained for all requests. These cookies have a long shelf life and can be used for days. I have tested and it works. Only one cookie "cf_clearance" is needed.

**Comment by saeeddhqan** [comment]
Does google captcha relate to btdig.com?

**Comment by saeeddhqan** [comment]
Only one cookie "cf_clearance" is needed: I think it's the best way. using proxies doesn't work.

**Comment by vikas-kundu** [comment]
> Does google captcha relate to btdig.com?

Yes, as soon you will visit the page it asks for Captcha. So, the user can fill it and obtain the cf_clearance cookie which can be used to scrap rest of data.

**Comment by vikas-kundu** [comment]
> Only one cookie "cf_clearance" is needed: I think it's the best way. using proxies doesn't work.

Proxy is for place like India where the government has blocked this website.

**Comment by saeeddhqan** [comment]
okay
