### ISSUE TITLE
Voice IO functions

### ISSUE THREAD

**Issue by anuran-roy** [saeeddhqan/Maryam#213]
As @k4u5h1k suggested, we can add NLP functions in Issue #212 . I suggest to add speech-to-text and text-to-speech functions. Can I work on it? The speechrecognition and pyttsx3 (or gTTS) modules may help.

**Comment by rachejazz** [comment]
speech to text in OSINT? I am curious how useful can it be?

**Comment by anuran-roy** [comment]
For faster workflows. Since @k4u5h1k is adding NLP, we just need to add s2t and t2s features.

Like since we're implementing NLP functions, some stuff can be done with it right?

**Comment by saeeddhqan** [comment]
@k4u5h1k won't add the NLP section. he just wants to add a class for finding the definition of words.
This feature cannot be added to the core project. But the user can install it from plugins.

**Comment by rachejazz** [comment]
I'm still curious how s2t will come into play while using Maryam.
Like for example, I launch Maryam (cli/web whatever) on my pc, then?
Considering none is using Windows here, how is it that it'll make faster workflows?

**Comment by anuran-roy** [comment]
Uh well... saving time while typing long commands. We'll soon be making a templating section for writing workflows faster... To make it even faster, we're considering an s2t plugin.

**Comment by k4u5h1k** [comment]
Add it to [mexts](https://github.com/mexts/init). Surely s2t can come in clutch somewhere.
