### ISSUE TITLE
[New Feature] Adding exactseek.com

### ISSUE THREAD

**Issue by rachejazz** [saeeddhqan/Maryam#219]
Here's a simple query:
https://www.exactseek.com/cgi-bin/search.cgi?q=security
Website claims on giving good seo based results.
Looks the contrary, extremely helpful for OSINT

**Comment by rachejazz** [comment]
Also adding https://www.sonicrun.com/cgi-bin/search.cgi?query=OSINT with this

**Comment by saeeddhqan** [comment]
no

**Comment by rachejazz** [comment]
@saeeddhqan any particular reason to it?

**Comment by saeeddhqan** [comment]
the results haven't enough quality and some of them are irrelevant as we have better search modules.
