### ISSUE TITLE
[Bug] in Reddit Module and few other Modules

### ISSUE THREAD

**Issue by bushra2001** [saeeddhqan/Maryam#225]
As pointed by @vikas-kundu , there are some errors in modules/search/reddit.py;

42. name = engine.__init__.__name__
43. q = f"{name}_q" if f"{name}_q" in q_formats else q_formats['default_q']

Line 42 is causing name= init, such that q is always set to  q_formats['default_q'] despite whatever the search engine. 
In picture 1 q is set to site:www.reddit.com microsoft instead of "www.reddit.com" microsoft

pic 1 without changes and pic 2 is after changes

![pic1](https://user-images.githubusercontent.com/61081924/117523511-34471a00-afd2-11eb-87a9-3678f7f0487a.png)
![pic2](https://user-images.githubusercontent.com/61081924/117523510-33ae8380-afd2-11eb-9fd9-4f4cfe27f9cc.png)

**Comment by bushra2001** [comment]
Similar kind of bugs are found in Linkedin, and other modules. I will find them and resolve asap.

**Comment by rishi23root** [comment]
This is a module error so just install the modules 
![image](https://user-images.githubusercontent.com/66913499/117532552-c1f02d00-b005-11eb-941e-af3dab901607.png)
 - `python3 -m pip install -r requirements`

## I didn't get any error 
![image](https://user-images.githubusercontent.com/66913499/117532595-f368f880-b005-11eb-8157-8da91d812f84.png)
Try to make branch even with saeeddhqan:master.

https://docs.github.com/en/github/getting-started-with-github/getting-changes-from-a-remote-repository

**Comment by vikas-kundu** [comment]
@rishabhjainfinal  You didn't get any result either. The bug is regarding that.

**Comment by anuran-roy** [comment]
> Similar kind of bugs are found in Linkedin, and other modules. I will find them and resolve asap.

The LinkedIn module was working a few days ago. Maybe some recent commits broke it?

**Comment by vikas-kundu** [comment]
> 
> 
> > Similar kind of bugs are found in Linkedin, and other modules. I will find them and resolve asap.
> 
> The LinkedIn module was working a few days ago. Maybe some recent commits broke it?

Linkedin and most of such modules are fine in general just a few search engine options in them are buggy .
