### ISSUE TITLE
Yippy Search Engine is redirecting to DuckDuckGo

### ISSUE THREAD

**Issue by bushra2001** [saeeddhqan/Maryam#226]
As pointed by @vikas-kundu , [yippy.com](https://yippy.com/) is redirecting to [duckduckgo.com ](https://duckduckgo.com/). The fate and future of the site is unknown according to Wikipedia. As it doesn't work any longer so its util class is redundant and should be removed as we already have duckduckgo. Moreover it should be removed from q_formats, and in sources, yippy should be replaced by duckduckgo. Kindly approve this issue, so that I can work on PR.

**Comment by saeeddhqan** [comment]
remove it from all sources and modules.

**Comment by vikas-kundu** [comment]
> 
> 
> remove it from all sources and modules.

and also the yippy util class is useless now i guess so, it should be removed too?

**Comment by saeeddhqan** [comment]
of course.
