### ISSUE TITLE
cannot pickle '_io.TextIOWrapper' object on python 3.9

### ISSUE THREAD

**Issue by kidmose** [saeeddhqan/Maryam#246]
I got this error with python 3.9 on OSX:
> cannot pickle '_io.TextIOWrapper' object

going back to python 3.7 things works fine.

Inspired by: https://github.com/GoogleCloudPlatform/gsutil/issues/961

**Comment by k4u5h1k** [comment]
This is caused by 3.8 and 3.9 changing the default process start method from _fork_ to _spawn_. Manually setting start method to fork fixes the issue.
Solved in commit d752f17dc9e9fdd68c9ef994cb2fbcad30593b1a.
