### ISSUE TITLE
installation commands are incorrect 

### ISSUE THREAD

**Issue by shubhangi013** [saeeddhqan/Maryam#255]
On the wiki page, the installation command should be : 
`git clone https://github.com/saeeddhqan/Maryam.git`
and 
`cd Maryam` (this should especially be changed as there is a folder called maryam in the repository)
![Screenshot from 2021-11-17 00-57-57](https://user-images.githubusercontent.com/78342516/142053322-ad7263f8-f3df-4f91-8db5-1fac1c035071.png)

**Comment by saeeddhqan** [comment]
solved.
