### ISSUE TITLE
Multiprocessing issue python 3.8 on macOS Monterey

### ISSUE THREAD

**Issue by moshaad7** [saeeddhqan/Maryam#256]
`[maryam][default] > maryam -e youtube -q "maryam"
[*] Command: maryam -e youtube -q "maryam"

[!] [nil:nil] File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 243, in set_start_method.
[!] [nil:nil] RuntimeError: context has already been set.
[maryam][default] >`

Possible Reason:
Python 3.8 on MacOS by default now uses "spawn" instead of "fork" as start method for new processes. 

 Proposed solution:
 multiprocessing.set_start_method("fork")

**Comment by saeeddhqan** [comment]
I think you used Maryam inside Maryam. Is that right?
In order to run youtube inside the framework, just run: `youtube -q "query"`
We solved this problem months ago. [here](https://github.com/saeeddhqan/Maryam/blob/799184f22c5f717e9eb70d9071dafd6380091abd/maryam/core/initial.py#L416) is the solution

**Comment by moshaad7** [comment]
<img width="1338" alt="terminal screenshot" src="https://user-images.githubusercontent.com/65341373/143267179-685d156a-2b25-498c-83af-b13dce03748b.png">

It's not working both the ways

**Comment by saeeddhqan** [comment]
Since I do not use a mac, I cannot evaluate and solve the problem. @k4u5h1k, could you please check this issue with your mac?

**Comment by k4u5h1k** [comment]
Hey! I am aware that macos uses spawn as the default start method, and am setting it to fork in the `run_tool` function of [initial.py](https://github.com/saeeddhqan/Maryam/blob/master/maryam/core/initial.py). I shall look into this issue and meanwhile I suggest you use python3.7.

Update: I have fixed the issue by adding a `force=True` argument to `set_start_method`.

**Comment by k4u5h1k** [comment]
Fixed in d4b7a5d667e1ef8b6261411ea0b5b080f1375502
