### ISSUE TITLE
Carrot2 not working 

### ISSUE THREAD

**Issue by moshaad7** [saeeddhqan/Maryam#257]
I am getting an error message "**ETOOLS is missed**" when using carrot2.

**Commands I used:** 
- iris -q "owasp maryam"
- carrot2 -q "owasp maryam"

<img width="1033" alt="Screenshot 2021-12-05 at 1 38 44 PM" src="https://user-images.githubusercontent.com/65341373/144738980-81874170-2f18-4a34-821c-3b2f72341d5a.png">

**Possible cause**
It's an internal problem with carrot2 and etools as I am facing some issue while using https://search.carrot2.org/#/search/web.
![image](https://user-images.githubusercontent.com/65341373/144739032-9ecfa1bb-1262-43d0-bf10-20d0847a4029.png)

**Comment by saeeddhqan** [comment]
It's because of your IP address. turn off your VPN or try later. I saw a key error that I solved right now.
