### ISSUE TITLE
Clustering Module only accepts .json file but not JSON object . 

### ISSUE THREAD

**Issue by moshaad7** [saeeddhqan/Maryam#258]
While developing a GUI for ( Iris Search + Cluster), I was using Maryam's webAPI module and found out that we need to save the result of Iris into a .JSON file and then Call Cluster API supplying JSON file.

**Problems** 
- This isn't a scalable solution when deploying web app (because we have to create JSON files for each user and for each query). 

**Proposed Solution**
- Have a unified api which can supply the result of Iris directly to Cluster as JSON object to process data at server side 

Please assign this task to me, 
After completing this task I will be developing a React UI which will consume this API and Layout visualization of Clusters

**Comment by saeeddhqan** [comment]
Give it a try
