### ISSUE TITLE
phone search error

### ISSUE THREAD

**Issue by cspidey** [saeeddhqan/Maryam#262]
while I using phone number search tool
I getting this error

[!] [phone_number_search:opt_proc] File "/usr/lib/python3/dist-packages/maryam/modules/osint/phone_number_search.py", line 40, in module_run.             
[!] [phone_number_search:opt_proc] KeyError: 'valid'.

**Comment by k4u5h1k** [comment]
will review and fix asap

**Comment by k4u5h1k** [comment]
Ah looks like numverify deprecated their demo api. The options now are to either delete the module or ask the user for a numverify api token. Will do one of those soon

**Comment by k4u5h1k** [comment]
fixed with https://github.com/saeeddhqan/Maryam/commit/37e3b79d92465bd64815852a13a974f7798f5e4b
