### ISSUE TITLE
Depreciation in cluster utility 

### ISSUE THREAD

**Issue by moshaad7** [saeeddhqan/Maryam#264]
In file maryam/core/util/iris/cluster.py , function get_feature_names is depreciated and will be removed in future versions. 
<img width="1383" alt="Screenshot 2022-01-27 at 8 35 23 PM" src="https://user-images.githubusercontent.com/65341373/151386336-37dd7e53-870b-456d-8baf-e23fbc1045a0.png">

**Comment by saeeddhqan** [comment]
@k4u5h1k please check it out.

**Comment by k4u5h1k** [comment]
sure. Will fix soon

**Comment by k4u5h1k** [comment]
done in 7ed3e06f364934162ba3ae12aaaa499185faf98c
