### ISSUE TITLE
Update your pip package

### ISSUE THREAD

**Issue by SofianeHamlaoui** [saeeddhqan/Maryam#266]
Here what happens when you install **Maryam** using PIP, you need to update your package to install the requirements manually or just add the requirement file to the resources.

![](https://i.imgur.com/YuHinGt.png)

**Comment by k4u5h1k** [comment]
Your command  is `pip install pip install maryam`. This is incorrect. Please use `pip install maryam` instead.

**Comment by SofianeHamlaoui** [comment]
> Your command is `pip install pip install maryam`. This is incorrect. Please use `pip install maryam` instead.

![!!](https://i.imgur.com/Fo2zbCS.png)

**Comment by k4u5h1k** [comment]
Looking into it. Meanwhile please try using `pip install maryam==2.5.0.post3`

**Comment by SofianeHamlaoui** [comment]
@k4u5h1k yes, now it's installing normally !

**Comment by k4u5h1k** [comment]
If you want the latest version please clone this repo and run `python3 setup.py install`

**Comment by k4u5h1k** [comment]
The pip package will be updated asap
