### ISSUE TITLE
Does the tool needs root permissions ? 

### ISSUE THREAD

**Issue by SofianeHamlaoui** [saeeddhqan/Maryam#267]
I want to know, does the tools needs root permissions to work ? or use the functionalities ?

**Comment by k4u5h1k** [comment]
No

**Comment by SofianeHamlaoui** [comment]
> No

You're using setuptools, that does choose by default the path : **/usr/lib/python3.10/site-packages/** for package installation, which does require root permissions to R&W.

if you run the script as a **non-root user,** you'll get an error : 

![!!](https://i.imgur.com/4M3wOK7.png)

To avoid that you need to add **--user** to the end of the command, probably cool to add it to the [installation Wiki](https://github.com/saeeddhqan/Maryam/wiki#installation). 

`python3 setup.py install --user`
