### ISSUE TITLE
Wiki examples outdated

### ISSUE THREAD

**Issue by z3y50n** [saeeddhqan/Maryam#27]
The examples located in the [wiki page](https://github.com/saeeddhqan/Maryam/wiki#examples) are not valid and need the following changes.

- To searching a RegExp to the web pages
    
    1.  `set url example.com` should be `set domain example.com`
    2.  `crawl` option is not valid
    
- Gain pdf files from search engine

    1. `set company EXAMPLE` should be `set query EXAMPLE`
    2.  `set type pdf` should be `set file pdf`
    3.  `metacrawler` option is not valid
    
- DNS brute force
    
    1.  `dnsbrute`, `wordlist` are not valid options
    2.  `set host example.com` should be `set domain example.com`

**Comment by saeeddhqan** [comment]
Fixed. thank you for informing me!
