### ISSUE TITLE
Support for termux

### ISSUE THREAD

**Issue by ghost** [saeeddhqan/Maryam#270]
Hello I am a termux user. It is have termux support? 
if it doest have what should i can use?

**Comment by k4u5h1k** [comment]
Yes Termux is simply a terminal emulator I do not see why Maryam would not work in it. Have you tried using it? If yes what problems did you face?

**Comment by ghost** [comment]
Hello sir, Thanks for feedback.

Yeah I tried to setup but it says a SystemError

First this error: WARNING: The wheel package is not available.

And at the end setup give this error:

SystemError("One of the required function to build numpy is not"
      SystemError: One of the required function to build numpy is not
available (the list is ['sin', 'cos', 'tan', 'sinh', 'cosh', 'tanh',
'fabs', 'floor', 'ceil', 'sqrt', 'log10', 'log', 'exp', 'asin', 'acos',
'atan', 'fmod', 'modf', 'frexp', 'ldexp']).
      [end of output]
  note: This error originates from a subprocess, and is likely not a
problem with pip. ERROR: Failed building wheel for numpy ERROR: Failed to
build one or more wheels error: Command
'['/data/data/com.termux/files/usr/bin/python3', '-m', 'pip',
'--disable-pip-version-check', 'wheel', '--no-deps', '-w',
'/data/data/com.termux/files/usr/tmp/easy_install-q07cdt31/gensim-4.2.0/temp/tmpys2r2_gw',
'--quiet', 'numpy>=1.17.0']' returned non-zero exit status 1.


I dont have a rooted phone, so i dont use sudo command. I just write:
python3 setup.py install

Thats all.

6 Ara 2022 Sal 10:41 tarihinde Kaushik Sivashankar ***@***.***>
şunu yazdı:

**Comment by k4u5h1k** [comment]
Perhaps Android does not have support for certain Python features that we are using, try installing Maryam on a PC system.

**Comment by ghost** [comment]
But i dont have a computer. Never mind i buy a PC next year so np

8 Ara 2022 Per 12:05 tarihinde Kaushik Sivashankar ***@***.***>
şunu yazdı:
