### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by einsidhe** [saeeddhqan/Maryam#281]
After installation just 'maryam' doesn't run.
To run it do 'python3 .local/lib/python3.10/site-packages/maryam'

**Comment by k4u5h1k** [comment]
No you shouldn't have to do that. Please check whether the folder where pip is adding the executable is in your PATH. For me the executable goes to `~/.local/bin/maryam` and because my PATH includes `~/.local/bin`, I am able to run `maryam` as command
