### ISSUE TITLE
Show modules is empty

### ISSUE THREAD

**Issue by ghost** [saeeddhqan/Maryam#282]
I reinstalled several times, but the error did not disappear.
![image](https://github.com/saeeddhqan/Maryam/assets/95542529/c21edb67-c561-43f0-8763-039e2a3cf626)

**Comment by k4u5h1k** [comment]
Please include python version and the command you used to install Maryam. Thanks!

**Comment by saeeddhqan** [comment]
@greenhell1337 @k4u5h1k working on it.

**Comment by saeeddhqan** [comment]
@greenhell1337 solved.
