### ISSUE TITLE
Bug in email_pwned request

### ISSUE THREAD

**Issue by vomanc** [saeeddhqan/Maryam#286]
Kali 2024.2
Python 3.11.9
___________________________________________________________________________________
[maryam][first_test] > email_pwned -e xxxxxxxxxgmail.com
[*] [PAWNED] Searching for pwning...
[!] [email_pwned:opt_proc] File "/usr/lib/python3/dist-packages/requests/models.py", line 975, in json.
[!] [email_pwned:opt_proc] Requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0).
[maryam][first_test] >

**Comment by saeeddhqan** [comment]
solved
