### ISSUE TITLE
Working for Reddit search module

### ISSUE THREAD

**Issue by ktg-123** [saeeddhqan/Maryam#31]
I am thinking to work on the Reddit OSINT module and will soon send a PR linked to it.

**Comment by saeeddhqan** [comment]
Some notes:
- Checking several search engines to get acquainted with their ability on your purpose. 
- Try to extract more information than just a URL(usernames, questions, etc).
- If you need a source that is not in the util classes, call me to help you to add a new util class.

Thank you for your help, in advance

**Comment by saeeddhqan** [comment]
Will be done by the #44 pull request
