### ISSUE TITLE
Bing Search Engine not working

### ISSUE THREAD

**Issue by z3y50n** [saeeddhqan/Maryam#47]
When I use the `search/bing` module I get this for every query

![image](https://user-images.githubusercontent.com/33282622/109947374-ebc56480-7ce1-11eb-88aa-1db9358e0451.png)

Also it doesn't work for other modules that use bing engine (`search/linkedin` as an example in the following image).

![image](https://user-images.githubusercontent.com/33282622/109947905-7d34d680-7ce2-11eb-803b-d155f700e7f6.png)

I would like to work on fixing that issue.

*I used a print statement to show that no links are coming from bing.
**Even though the engine isn't set to use google it always uses it so that could maybe be a separate issue

**Comment by saeeddhqan** [comment]
Are you sure that you use the latest version?
Yes, it had a bug but I fixed it.
![m](https://user-images.githubusercontent.com/31902891/109956334-8b1e3380-7cb1-11eb-8bb0-207b8e919f97.png)

**Comment by saeeddhqan** [comment]
Fixed by #48
