### ISSUE TITLE
The soupsieve package is not installed.

### ISSUE THREAD

**Issue by nu11secur1ty** [saeeddhqan/Maryam#5]
You are late, my friends ;)
BR
So I've to use pip2 because I use pip3 to which I aliasing to pip however, do not wonder about this. ;) 

----------------------------------------------------------------------------
root@kali:/opt/Maryam# pip2 install -r requirements
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (from -r requirements (line 1)) (2.22.0)
Requirement already satisfied: lxml in /usr/local/lib/python2.7/dist-packages (from -r requirements (line 2)) (4.5.0)
Requirement already satisfied: bs4 in /usr/local/lib/python2.7/dist-packages (from -r requirements (line 3)) (0.0.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python2.7/dist-packages (from bs4->-r requirements (line 3)) (4.8.2)
Requirement already satisfied: soupsieve>=1.2 in /usr/local/lib/python2.7/dist-packages (from beautifulsoup4->bs4->-r requirements (line 3)) (1.9.5)
Requirement already satisfied: backports.functools-lru-cache; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from soupsieve>=1.2->beautifulsoup4->bs4->-r requirements (line 3)) (1.6.1)

----------------------------------------------------------------------------------------------------------------------------
root@kali:/opt/Maryam# ./maryam
/usr/local/lib/python2.7/dist-packages/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
  'The soupsieve package is not installed. CSS selectors cannot be used.'
 ____     ____  ____ _   _  ____   ____  
|    \   / _  |/ ___) | | |/ _  | |    \ 
| | | | ( ( | | |   | |_| ( ( | | | | | |
|_|_|_|  \_||_|_|    \__  |\_||_| |_|_|_|
                    (____/

               v1.4.0

[7] osint modules
[4] footprint modules

[maryam][default] > 
[maryam][default] >

**Comment by saeeddhqan** [comment]
removed BS4 dependencies.
for py3 I try to do it

**Comment by nu11secur1ty** [comment]
ok, my friend ;)

**Comment by saeeddhqan** [comment]
Migrate to py3
