### ISSUE TITLE
[New Feature] Username Finder

### ISSUE THREAD

**Issue by prince-7** [saeeddhqan/Maryam#52]
An OSINT feature module, where the user can find all the accounts of a particular username.

**Comment by adviksinghania** [comment]
Hello, I would like to work on this feature.

**Comment by prince-7** [comment]
I am already working on this one. Thank you.

**Comment by prakhar-ai** [comment]
Hi @prince-7 , I just wanted to add that If you're still working on this, you can look at the [Sherlock](https://github.com/sherlock-project) project for reference.

**Comment by prince-7** [comment]
Yes I have referred that and have been working on it. Thank you.

**Comment by saeeddhqan** [comment]
Done by #94 and #91
