### ISSUE TITLE
[New Feature] Add Wayback Machine for domain snapshots

### ISSUE THREAD

**Issue by rachejazz** [saeeddhqan/Maryam#56]
For details: [the Internet Archive](https://archive.org)
Will be wonderful to enumerate early phases of a domain.

**Comment by slayer321** [comment]
Hey I will to work on this feature ... 
I'm new to open source so can you guide me how to start with it?

**Comment by rachejazz** [comment]
Hi @slayer321 , this is already taken by me. Those who raise NEW FEATURE issues are the ones who have been assigned. You can look at the todo list for any other job to be taken :)

**Comment by slayer321** [comment]
ok, thank you ........ can you direct me to the TODO list

**Comment by z3y50n** [comment]
It is under the projects tab

**Comment by slayer321** [comment]
ok will check it out .. thank you
