### ISSUE TITLE
[New Feature] Improved DNS enumeration search modules

### ISSUE THREAD

**Issue by rachejazz** [saeeddhqan/Maryam#57]
Probable good ideas I hav[securitytrails](https://securitytrails.com) e for future improvements in dns enumeration:

[urlscan](https://urlscan.io) : API for searching existing scans by attributes such as domains, IPs, Autonomous System (AS) numbers, hashes, etc.

[rapiddns](https://rapiddns.io) : Can query the domain name of the same IP website (support IPv6). You can also query subdomain information.

[hackertarget[PAID]](https://hackertarget.com) : This has a whole bunch of resources, I still need feedback on this

[Security trails](https://securitytrails.com)
I will start at the earliest once the above gets approved.

**Comment by saeeddhqan** [comment]
- The hackertarget is not appropriate.
- We already have rapiddns. Instead you can implement archive search engine.
- Urlscan is suitable.

**Comment by rachejazz** [comment]
All good. Thanks!
