### ISSUE TITLE
[New Feature] OSINT database updates

### ISSUE THREAD

**Issue by rachejazz** [saeeddhqan/Maryam#58]
Massive improvisation can be done if we try switching from search engines to large databases. The following had clicked with me.
While this stays very much far fetched yet since huge data needs to get stored in workspaces, I'm still skeptical about this idea
Please do check:

[Threatminer](https://www.threatminer.org/about.php)

[IntelX](https://intelx.io)

[Aleph](https://docs.alephdata.org/developers/alephclient)

[RIPE DB](https://rest.db.ripe.net)

[Rapid7](rapid7.com)

[ThreatCrowd](https://www.threatcrowd.org/domain.php?domain=yahoo.com)

This section highly needs feedback and can be started to be worked on gradually.

**Comment by vikas-kundu** [comment]
Also what about Shodan and Censys API ?

**Comment by rachejazz** [comment]
Hello @vikas-kundu I have already added Shodan API in #60 . Right now waiting for the new core push, I will start working on it more. 
I am guessing Censys is untaken :) You can get that approved if you want to

**Comment by hansikaSAXENA23** [comment]
Hello everyone!
I am a CS undergraduate looking for my debut in contributing to an Open-Source Project. How can I help and what in particular can I contribute to?

**Comment by rachejazz** [comment]
Hi @hansikaSAXENA23 ! Go through the https://github.com/saeeddhqan/maryam/wiki/Development-Guide
:)

**Comment by anuran-roy** [comment]
@rachejazz you may want to  use AlienVault OTX or the ThreatConnect databases. AlienVault has a free API that is rate limitedI guess. 
Do you want to take that up, or will someone else (read 'I' :P) work on it? 😅

**Comment by rachejazz** [comment]
@anuran-roy otx is already added🤔 you can see that under dns_search module. Ask @saeeddhqan if you can make a separate util class out of it.
As for Threat Connect, doesn't it need a user's license? Will it allow scraping for free?

**Comment by anuran-roy** [comment]
> @anuran-roy otx is already added you can see that under dns_search module. Ask @saeeddhqan if you can make a separate util class out of it.
> As for Threat Connect, doesn't it need a user's license? Will it allow scraping for free?

@rachejazz ThreatConnect has an API itself. I don't think we need to scrape it. 😄

**Comment by rachejazz** [comment]
You're right! It's asking for a sign in for an API key though. Let's deal with this during the summer maybe?
The ones I've listed above need not sign and gives data for free. 

I'm guessing after I add these, we can still think how much ThreatConnect can get us different results. Thank you for the find too

**Comment by anuran-roy** [comment]
You're most welcome @rachejazz 😄 I'll try dealing with this and a few other finds this Summer 😃

**Comment by saeeddhqan** [comment]
@hansikaSAXENA23 
Look at the previous pull requests and TODO list in the project section, select one of them and work on it.

**Comment by necrose99** [comment]
https://github.com/qeeqbox/social-analyzer
API, CLI & Web App for analyzing & finding a person's profile across 400+ social media \ websites (Detections are updated regularly)
