### ISSUE TITLE
[New Feature] Find CVEs

### ISSUE THREAD

**Issue by z3y50n** [saeeddhqan/Maryam#63]
It would be very useful if the tool could search for Common Vulnerabilities and Exposures based on `id` or `name`.

Ideally in the future we could automatically detect the CVEs of a given website.

**Comment by saeeddhqan** [comment]
You can work on it. 
If you need a new source to search let me know.
Thank you!

**Comment by z3y50n** [comment]
I thinks these 3 sources are all we need for this module:

- https://nvd.nist.gov/vuln/search
- https://cve.mitre.org/cve/search_cve_list.html
- https://www.cvedetails.com/index.php

**Comment by saeeddhqan** [comment]
www.cvedetails.com is used the Google engine to search so we can implement it by self.google.
What do you want to extract from https://nvd.nist.gov/vuln/search and https://cve.mitre.org/cve/search_cve_list.html? SVE and description?

**Comment by z3y50n** [comment]
Yes I was thinking we can have: id, link and description

Also since in all cases the data are coming from a `<table>` it could be easier to use an HTML parser (ex. `BeautifulSoup`) instead of regex to get the data but I don't know if you are willing to make the tool require more dependencies.

**Comment by saeeddhqan** [comment]
Sure, you can add BeautifulSoup to the requirements.

**Comment by saeeddhqan** [comment]
Done by #65
