### ISSUE TITLE
Add the darksearch.io search engine

### ISSUE THREAD

**Issue by ktg-123** [saeeddhqan/Maryam#67]
This module would help to identify dark web services. I would like to work upon this

**Comment by saeeddhqan** [comment]
Okay.
About your slack message, the dns_search has been implemented like what you said.
Create a PR for repeated codes so I can help you to do that. we need to add thread supporting like OSINT modules and a stand-alone function to call each engine.

**Comment by ktg-123** [comment]
Sure, I will create a PR soon related to that

**Comment by saeeddhqan** [comment]
Done by #68
