### ISSUE TITLE
[New Feature] Checking the enumerated email assocaited with a domain in data leak dumps

### ISSUE THREAD

**Issue by vikas-kundu** [saeeddhqan/Maryam#74]
Emails enumerated while scanning can be checked from [haveibeenpwned.com](https://www.haveibeenpwned.com). Their API can be used for this purpose same.
Reference: https://haveibeenpwned.com/API/v2

**Comment by vikas-kundu** [comment]
Can I work on this module. Where domain would be necessarily required to see if its been a part of a data breach and email part is optional?

**Comment by saeeddhqan** [comment]
Does it need an API key?
We do not support sources that need an API key.

**Comment by vikas-kundu** [comment]
Unfortunately it does. I am looking for any free resource if available. Otherwise should I try scraping from haveibeenpwned ?

**Comment by saeeddhqan** [comment]
I'm afraid. But it isn't good. You can work on the Github Search module if you want to contribute. We need a Github search module, which interacts with Github by user cookie.

**Comment by rachejazz** [comment]
@saeeddhqan i thought @ktg-123 already is done with it? iirc, it was assigned to me. Waiting for the new core and the PRs merged. I will add them :)

**Comment by vikas-kundu** [comment]
@saeeddhqan So, interestingly while researching for the same, i found their xmlHttp request API. So managed to put together a script which can check emails from data breaches using their API via python's cloudscraper. [This is the script ](https://github.com/vikas-kundu/pwnscrap). So, should I work on a module for the same?

**Comment by saeeddhqan** [comment]
Yes, you can. but don't use cloudscraper.

**Comment by vikas-kundu** [comment]
@saeeddhqan actually this endpoint is present within the haveibeenpwned website. So, cloudscraper is necessary because it is protected by Cloudflare like the rest of the website.

**Comment by rachejazz** [comment]
Did cloudscraper successfully bypass the check? I ran it last week, it said Cloudflare changed it's check params again

**Comment by vikas-kundu** [comment]
I wrote [this script](https://github.com/vikas-kundu/pwnscrap) only a few hours ago. Was able to scrap successfully for me.

**Comment by vikas-kundu** [comment]
@saeeddhqan i have complete the email_pwned module. Should i issue a pull request ?

**Comment by saeeddhqan** [comment]
yes, please
