### ISSUE TITLE
Problems launching ./maryam

### ISSUE THREAD

**Issue by DarkReitor** [saeeddhqan/Maryam#8]
The file has the privileges.
![image](https://user-images.githubusercontent.com/45410348/79534378-01855900-8040-11ea-8efd-2f447071dfd2.png)

**Comment by djtroby** [comment]
Getting error while executing !!!

SyntaxError: invalid syntax
root@k2020:~/Maryam# ./maryam 
Traceback (most recent call last):
  File "./maryam", line 34, in <module>
    from core import base
  File "/root/Maryam/core/base.py", line 33, in <module>
    from core import framework
  File "/root/Maryam/core/framework.py", line 318
    async = [self.to_unicode_str(x[i]) if x[i] != None else '' for x in tdata]

**Comment by w1ld3r** [comment]
Got the same error.
Code quality A with this `async = [self.to_unicode_str(x[i]) if x[i] != None else '' for x in tdata]` ?

**Comment by DarkReitor** [comment]
> Got the same error.
> Code quality A with this `async = [self.to_unicode_str(x[i]) if x[i] != None else '' for x in tdata]` ?

Try to modify the code on my own, if you read it like it can't find the base module but in the syntax if I don't know all the code I can't do anything. I am surprised that there are few reports.

Maybe some variable is missing.

**Comment by w1ld3r** [comment]
I'm looking at it

**Comment by w1ld3r** [comment]
The problem is just because async can't be used as a variable name.
You can replace it by toto for example.

Furthermore I've modify a little bit your beautiful oneline:
toto = [['', self.to_unicode_str(x[i])][x[i]!=None] for x in tdata]

**Comment by DarkReitor** [comment]
Indeed

> The problem is just because async can't be used as a variable name.
> You can replace it by toto for example.
> 
> Furthermore I've modify a little bit your beautiful oneline:
> toto = [['', self.to_unicode_str(x[i])][x[i]!=None] for x in tdata]

Indeed!!!. That fix the hole thing.
