### ISSUE TITLE
[New Feature] Adding Additional Search Modules

### ISSUE THREAD

**Issue by prakhar-ai** [saeeddhqan/Maryam#81]
We currently have search modules for most social networks, with a few popular exceptions (Twitch, Pinterest, TikTok, etc). I would like to add new modules for these.

**Comment by saeeddhqan** [comment]
Great. You can work on it and make PR so I'll help you.
If you want, send me your email to add you to the Slack Channel.

**Comment by prakhar-ai** [comment]
Hello @saeeddhqan, Thank you. I'm already part of the Slack Channel. I'll get started with the PR.

**Comment by saeeddhqan** [comment]
For each addition, one issue.
