### ISSUE TITLE
[New Feature] Adding ipinfo.io to osint modules

### ISSUE THREAD

**Issue by 0xrishabh** [saeeddhqan/Maryam#87]
Adding ipinfo.io as a module to search for data about IP instantly.

**Comment by rachejazz** [comment]
@0xrishabh are you working on this?

**Comment by 0xrishabh** [comment]
yes @rachejazz

**Comment by saeeddhqan** [comment]
@0xrishabh Work on another thing. it isn't as good as a new module. It may be part of another module(dns_search?)

**Comment by 0xrishabh** [comment]
Should I add it in dns_search? Will that work? @saeeddhqan

**Comment by saeeddhqan** [comment]
Isn't it better to write a module based on this: http://whois.arin.net/rest/pocs;domain=google.com
? It finds employed people on Google. Even we can extract emails.

**Comment by 0xrishabh** [comment]
@saeeddhqan  it is maybe better, but it is only for domains. There are many cases in which the user will want to search for IP in that case the ipinfo module works better
