### ISSUE TITLE
[Bug] Issue when typing long commands

### ISSUE THREAD

**Issue by z3y50n** [saeeddhqan/Maryam#89]
The issue can be seen on the gif below.

![Peek 2021-03-21 16-00](https://user-images.githubusercontent.com/33282622/111907735-51924a00-8a5f-11eb-8581-94728ec42689.gif)

**Comment by rachejazz** [comment]
Funny. I'm taking this and will solve it soon

**Comment by saeeddhqan** [comment]
It happens just in the 2.0 version:
![Screenshot 2021-03-21 18:13:28](https://user-images.githubusercontent.com/31902891/111916884-81d3eb80-8a53-11eb-9d15-e8764d3ed34c.png)

**Comment by saeeddhqan** [comment]
Fixed.
