### ISSUE TITLE
[Bug] Error in handling keyboard interrupt

### ISSUE THREAD

**Issue by ktg-123** [saeeddhqan/Maryam#92]
When I first run a module and after gathering the results when I then try to exit from interface by using Ctrl + C. Then instead of showing
 `[!] Use exit command to exit (or press enter to continue)` 
it shows 
`Stopping <module name> module(press enter to continue)...`
 although the module has completed the execution.

**Comment by ktg-123** [comment]
I would like to fix this issue

**Comment by ktg-123** [comment]
I think it is because of the way signal module handles exception. Could you please tell the reason for using signal module?
Although,  I am able to fix it by handling KeyboardInterrupt in the `try-except` block. If it seems fine I will make a PR. 
Regards
![Peek 2021-03-23 08-52](https://user-images.githubusercontent.com/58258464/112088552-0b9bca00-8bb6-11eb-971d-df49ffcc3966.gif)

**Comment by saeeddhqan** [comment]
make PR
